package com.lp.ssm.mapper;

import com.lp.ssm.model.orderDetail;
import com.lp.ssm.model.orderDetailExample;
import com.lp.ssm.model.orderDetailKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface orderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Wed Nov 13 21:20:02 CST 2019
     */
    long countByExample(orderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Wed Nov 13 21:20:02 CST 2019
     */
    int deleteByExample(orderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Wed Nov 13 21:20:02 CST 2019
     */
    int deleteByPrimaryKey(orderDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Wed Nov 13 21:20:02 CST 2019
     */
    int insert(orderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Wed Nov 13 21:20:02 CST 2019
     */
    int insertSelective(orderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Wed Nov 13 21:20:02 CST 2019
     */
    List<orderDetail> selectByExample(orderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Wed Nov 13 21:20:02 CST 2019
     */
    orderDetail selectByPrimaryKey(orderDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Wed Nov 13 21:20:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") orderDetail record, @Param("example") orderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Wed Nov 13 21:20:02 CST 2019
     */
    int updateByExample(@Param("record") orderDetail record, @Param("example") orderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Wed Nov 13 21:20:02 CST 2019
     */
    int updateByPrimaryKeySelective(orderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Wed Nov 13 21:20:02 CST 2019
     */
    int updateByPrimaryKey(orderDetail record);
}