package com.lp.ssm.model;

public class orderDetailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.order_id
     *
     * @mbg.generated Wed Nov 13 21:20:02 CST 2019
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.items_id
     *
     * @mbg.generated Wed Nov 13 21:20:02 CST 2019
     */
    private Integer itemsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.order_id
     *
     * @return the value of orderdetail.order_id
     *
     * @mbg.generated Wed Nov 13 21:20:02 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.order_id
     *
     * @param orderId the value for orderdetail.order_id
     *
     * @mbg.generated Wed Nov 13 21:20:02 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.items_id
     *
     * @return the value of orderdetail.items_id
     *
     * @mbg.generated Wed Nov 13 21:20:02 CST 2019
     */
    public Integer getItemsId() {
        return itemsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.items_id
     *
     * @param itemsId the value for orderdetail.items_id
     *
     * @mbg.generated Wed Nov 13 21:20:02 CST 2019
     */
    public void setItemsId(Integer itemsId) {
        this.itemsId = itemsId;
    }
}